# hurst.py

# Copyright (C) 2025 Matheus Rolim Sales
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from typing import Tuple, Union

import numpy as np
from numpy.typing import NDArray

from pynamicalsys.common.time_series_metrics import hurst_exponent
from pynamicalsys.common.types import int_t, map_t
from pynamicalsys.discrete_time.trajectory import generate_trajectory


def hurst_exponent_wrapped(
    u: NDArray[np.float64],
    parameters: NDArray[np.float64],
    total_time: int_t,
    mapping: map_t,
    wmin: int = 2,
    transient_time: int_t | None = None,
    return_last: bool = False,
) -> NDArray[np.float64]:
    """
    Compute the Hurst exponent of each component of a trajectory generated by a
    discrete-time dynamical system.

    Parameters
    ----------
    u : NDArray[np.float64]
        Initial condition of shape `(neq,)`, where `neq` is the system dimension.
    parameters : NDArray[np.float64]
        Parameter array passed to `mapping`.
    total_time : int_t
        Total number of iterations used to generate the trajectory.
    mapping : map_t
        Function defining the time evolution of the system.
    wmin : int, optional
        Minimum window size used in the rescaled-range analysis. Default is `2`.
    transient_time : int_t | None, optional
        Number of initial iterations discarded before computing the trajectory.
        If None, no transient is discarded.
    return_last : bool, optional
        If True, return the Hurst exponents concatenated with the final state of
        the trajectory. Otherwise, return only the Hurst exponents.

    Returns
    -------
    NDArray[np.float64]
        - If `return_last=False`, returns a 1D array of shape `(neq,)`
          containing the Hurst exponent of each component.
        - If `return_last=True`, returns a 1D array of shape `(2 * neq,)`
          containing:
            - the Hurst exponents in the first `neq` entries
            - the final state of the trajectory in the last `neq` entries

    Notes
    -----
    This is a low-level helper used by the system wrappers. Input validation is
    expected to be handled by the wrapper.
    """
    u = u.copy()
    neq = len(u)

    time_series = generate_trajectory(
        u=u,
        parameters=parameters,
        total_time=total_time,
        mapping=mapping,
        transient_time=transient_time,
    )

    h = hurst_exponent(time_series, wmin=wmin)

    if return_last:
        result = np.empty(2 * neq, dtype=np.float64)
        result[:neq] = h
        result[neq:] = time_series[-1, :]
        return result

    return h


def finite_time_hurst_exponent(
    u: NDArray[np.float64],
    parameters: NDArray[np.float64],
    total_time: int_t,
    finite_time: int_t,
    mapping: map_t,
    wmin: int = 2,
    return_points: bool = False,
) -> Union[NDArray[np.float64], Tuple[NDArray[np.float64], NDArray[np.float64]]]:
    """
    Compute finite-time Hurst exponents for a discrete-time dynamical system.

    The trajectory is split into consecutive non-overlapping windows of length
    `finite_time`. The Hurst exponent of each component is computed separately
    in each window.

    Parameters
    ----------
    u : NDArray[np.float64]
        Initial condition of shape `(neq,)`, where `neq` is the system dimension.
    parameters : NDArray[np.float64]
        Parameter array passed to `mapping`.
    total_time : int_t
        Total number of iterations used in the computation.
    finite_time : int_t
        Length of each non-overlapping analysis window.
    mapping : map_t
        Function defining the time evolution of the system.
    wmin : int, optional
        Minimum window size used in the rescaled-range analysis. Default is `2`.
    return_points : bool, optional
        If True, also return the final phase-space point of each window.

    Returns
    -------
    NDArray[np.float64] or Tuple[NDArray[np.float64], NDArray[np.float64]]
        - If `return_points=False`, returns an array of shape
          `(num_windows, neq)` containing the finite-time Hurst exponents.
        - If `return_points=True`, returns:
            - `h_values`: array of shape `(num_windows, neq)` with the finite-time
              Hurst exponents
            - `phase_space_points`: array of shape `(num_windows, neq)` with the
              final state of each window

    Notes
    -----
    This is a low-level helper used by the system wrappers. Input validation is
    expected to be handled by the wrapper.
    """
    u = u.copy()
    neq = len(u)

    num_windows = total_time // finite_time
    h_values = np.zeros((num_windows, neq), dtype=np.float64)
    phase_space_points = np.zeros((num_windows, neq), dtype=np.float64)

    for i in range(num_windows):
        time_series = generate_trajectory(
            u=u,
            parameters=parameters,
            total_time=finite_time,
            mapping=mapping,
        )
        h_values[i] = hurst_exponent(time_series, wmin=wmin)
        phase_space_points[i] = time_series[-1, :]
        u = time_series[-1, :].copy()

    if return_points:
        return h_values, phase_space_points

    return h_values
